import { config } from '../config';
/** Internal simulator ONLY. Never used when EXPO_PUBLIC_APP_MODE=connected. No real credentials. */
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Crypto from 'expo-crypto';
const KEY = 'firstlane-v3-demo-accounts';
export interface Identity { id: string; email: string; name: string; confirmed: boolean; }
type RecordEntry = { identity: Identity; salt: string; hash: string; paid?: { startsAt: string; lifetime: true; revokedAt?: string }; receipts?: any[]; };
async function db(): Promise<Record<string, RecordEntry>> { if (config.mode !== 'demo') throw new Error('Test accounts are disabled.'); return JSON.parse(await AsyncStorage.getItem(KEY) || '{}'); }
async function put(value: any) { await AsyncStorage.setItem(KEY, JSON.stringify(value)); }
async function hash(password: string, salt: string) { return Crypto.digestStringAsync(Crypto.CryptoDigestAlgorithm.SHA256, `${salt}:${password}`); }
export function validateCredentials(email: string, password: string) { if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) throw new Error('Enter a valid email address.'); if (password.length < 8) throw new Error('Use at least 8 characters for your password.'); }
export async function demoRegister(email: string, password: string, name: string) { validateCredentials(email, password); const all = await db(), key = email.trim().toLowerCase(); if (all[key]) throw new Error('This preview email already exists. Sign in instead.'); const salt = Crypto.randomUUID(); all[key] = { identity: { id: Crypto.randomUUID(), email: key, name, confirmed: false }, salt, hash: await hash(password, salt), receipts: [] }; await put(all); }
export async function demoVerify(email: string, code: string) { if (code !== '246810') throw new Error('Use the preview code 246810.'); const all = await db(), entry = all[email.toLowerCase()]; if (!entry) throw new Error('Create your preview account first.'); entry.identity.confirmed = true; await put(all); await AsyncStorage.setItem('firstlane-v3-demo-session', JSON.stringify(entry.identity)); return entry.identity; }
export async function demoSignIn(email: string, password: string) { const entry = (await db())[email.trim().toLowerCase()]; if (!entry || entry.hash !== await hash(password, entry.salt)) throw new Error('Email or password did not match.'); if (!entry.identity.confirmed) throw new Error('Verify your email with the preview code first.'); await AsyncStorage.setItem('firstlane-v3-demo-session', JSON.stringify(entry.identity)); return entry.identity; }
export async function demoSession(): Promise<Identity | null> { const saved = JSON.parse(await AsyncStorage.getItem('firstlane-v3-demo-session') || 'null'); if (!saved) return null; const entry = (await db())[saved.email]; return entry?.identity.confirmed ? entry.identity : null; }
export async function demoLogout() { await AsyncStorage.removeItem('firstlane-v3-demo-session'); }
export async function demoRecords(identity: Identity) { return (await db())[identity.email] || {}; }
export async function demoPurchase(identity: Identity) { const all = await db(), entry = all[identity.email]; if (!entry?.identity.confirmed) throw new Error('Sign in before checkout.'); if (entry.paid && !entry.paid.revokedAt) throw new Error('Ontario G1 Complete is already unlocked.'); entry.paid = { startsAt: new Date().toISOString(), lifetime: true }; entry.receipts = [...(entry.receipts || []), { id: Crypto.randomUUID(), createdAt: new Date().toISOString(), amount: config.offer.label, status: 'simulated', lifetime: true }]; await put(all); return entry; }
export async function demoResetPassword(email: string, code: string, password: string) { validateCredentials(email, password); if (code !== '246810') throw new Error('Use the preview recovery code 246810.'); const all = await db(), entry = all[email.toLowerCase()]; if (!entry) throw new Error('No preview account found.'); entry.salt = Crypto.randomUUID(); entry.hash = await hash(password, entry.salt); await put(all); }
export async function demoDelete(identity: Identity) { const all = await db(); delete all[identity.email]; await put(all); await demoLogout(); }
