from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[1]
css=(root/'preview/style.css').read_text(encoding='utf-8');script=(root/'preview/app.js').read_text(encoding='utf-8');commerce=(root/'preview/commerce.js').read_text(encoding='utf-8');access=(root/'src/domain/access.mjs').read_text(encoding='utf-8').replace('export function','function').replace('export const','const');samples=(root/'content/sample-manifest.json').read_text(encoding='utf-8');engine=(root/'src/domain/engine.mjs').read_text(encoding='utf-8').replace('export function','function')
bank=json.loads((root/'content/ontario-g1.draft.json').read_text(encoding='utf-8'));art={n:(root/f'assets/{n}.svg').read_text(encoding='utf-8').replace('<svg ', '<svg style="width:100%;height:100%" ', 1) for n in ['logo','journey','road','trophy']}
icontext=(root/'src/components/Icon.tsx').read_text(encoding='utf-8');icons=re.search(r'const paths[^=]*=\s*(\{.*?\n\});',icontext,re.S).group(1)
pages=['verify-email','checkout','payment-success','membership','reset-password','locked','welcome','destination','goal','today','study','topic','quiz','exam','results','session-review','question','review','saved','progress','history','profile','plans','jurisdiction','study-plan','downloads','appearance','account','sign-in','sign-up','forgot-password','support','report','content','legal']
options=''.join(f'<option value="{p}">{p.replace("-"," ").title()}</option>' for p in pages)
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>FirstLane — Interactive design preview</title><style>'''+css+'''</style></head><body><div class="studio"><aside class="studio-side"><div class="studio-brand">'''+art['logo']+'''FirstLane</div><h1>Get road ready.</h1><p>A calm, considered driving-preparation experience. Explore the screens, try a session, and make yourself comfortable.</p><div class="studio-label">MAKE IT YOURS</div><div class="studio-controls"><button onclick="setTheme('light')">Daylight</button><button onclick="setTheme('dark')">Night drive</button></div><div class="studio-label">EXPLORE THE EXPERIENCE</div><select id="screen-picker" aria-label="Jump to a screen" onchange="go(this.value)">'''+options+'''</select><div class="studio-controls" style="margin-top:12px"><button onclick="go('welcome')">Start the journey</button><button onclick="reset()">Reset demo</button></div><p class="studio-foot">INTERACTIVE DESIGN COMPANION<br>Not a native simulator or a live service. This local preview uses the same draft questions, learning engine, illustrations and design direction as the React Native source. Local test accounts and simulated receipts only. No real email, charges or network requests.</p></aside><main class="phone" id="phone"><div class="status" aria-hidden="true"><span>9:41</span><div class="status-symbols"><div class="signal"><i></i><i></i><i></i><i></i></div><span style="font-size:13px">⌁</span><span class="battery"></span></div></div><div id="screen"></div></main></div><script>'''
offer=(root/'src/domain/offer.mjs').read_text(encoding='utf-8').replace('export const','const')
access=re.sub(r'^import .*?;\s*', '', access, flags=re.M)
html+='<NO>'.replace('<NO>',offer+'\n')+'const BANK='+json.dumps(bank,ensure_ascii=False).replace('</','<\\/')+';\nconst ART='+json.dumps(art).replace('</','<\\/')+';\nconst ICONS='+icons+';\n'+engine+'\n'+access+'\nconst SAMPLES='+samples+';\n'+script+'\n'+commerce+'</script></body></html>'
(root/'preview/index.html').write_text(html,encoding='utf-8')
# Export a second standalone copy only when an explicit path is supplied.
import sys
if len(sys.argv)>1: Path(sys.argv[1]).write_text(html,encoding='utf-8')
print('Built preview:',len(html),'bytes')
