/* FirstLane v0.3 interactive companion: local simulator, NEVER a billing/authentication service. */
const COMMERCE_KEY='firstlane-commerce-preview-v3';
let commerce;try{commerce={accounts:{},active:null,storeOutcome:'success',...JSON.parse(localStorage.getItem(COMMERCE_KEY)||'null')};}catch{commerce={accounts:{},active:null,storeOutcome:'success'};}
function persistCommerce(){localStorage.setItem(COMMERCE_KEY,JSON.stringify(commerce));}
const freshStudy=()=>({...initial,name:'',sessions:[],bookmarks:[],reports:[],active:null,onboarded:true,access:false});
function currentAccount(){return commerce.active?commerce.accounts[commerce.active]:null;}
function currentIdentity(){return currentAccount()?.identity||null;}
function now(){return Date.now();}
function accessNow(){return resolveAccess(currentIdentity(),currentAccount()||{},now());}
function allowedNow(id){return canReadQuestion(id,accessNow(),SAMPLES);}
function samplePool(){return allowedQuestions(bank,accessNow(),SAMPLES);}
function storeStudy(){const account=currentAccount();if(account)account.study=structuredClone(state);else commerce.guest=structuredClone(state);persistCommerce();}
const originalSave=save;save=function(){originalSave();storeStudy();};
if(currentAccount())state={...freshStudy(),...currentAccount().study,name:currentAccount().identity.name||currentAccount().study?.name||''};
else if(commerce.guest)state={...freshStudy(),...commerce.guest};else{state.active=null;state.sessions=[];state.bookmarks=[];state.access=false;}
function returnTo(route){return ['checkout','plans'].includes(route)?route:'plans';}
function authNext(){return returnTo(data.next);}
function accessCard(){const a=accessNow();return `<div class="access-card"><div class="row between">${chip(a.label,a.full?'spark':'lock',a.full)}<strong class="small">${a.full?'500 questions':a.kind==='guest'?'10 samples':'40 samples'}</strong></div><p class="muted small">${escape(accessDescription(a,now()))}</p>${btn(a.full?'View purchase':a.kind==='guest'?'Create a free account':'Unlock Ontario — CA$14.99',`go('${a.full?'membership':a.kind==='guest'?'sign-up':'plans'}')`,a.full?'ghost':'secondary',a.full?'':'arrow')}</div>`;}
function ensureFeature(feature){if(canUseFeature(feature,accessNow()))return true;go('locked',{reason:feature});return false;}
function previewGuest(){storeStudy();commerce.active=null;state={...freshStudy(),...(commerce.guest||{})};state.onboarded=true;save();go('today');}
function validEmail(email){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);}
async function passwordHash(value,salt){if(!crypto.subtle)throw new Error('Open this preview on localhost to use test accounts.');const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(salt+':'+value));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function errorAt(message){const e=document.getElementById('form-error');if(e){e.textContent=message;e.hidden=false;}else toast(message);}
function formError(){return '<div id="form-error" class="note warning" role="alert" hidden></div>';}
function togglePassword(){const input=document.getElementById('password');input.type=input.type==='password'?'text':'password';const b=document.getElementById('show-password');if(b)b.textContent=input.type==='password'?'Show password':'Hide password';}
const passwordField=(label='Password')=>field(label,'password','At least 8 characters','password')+'<button id="show-password" class="text-button" style="align-self:flex-end" onclick="togglePassword()">Show password</button>';
async function createPreviewAccount(){const email=document.getElementById('email').value.trim().toLowerCase(),name=document.getElementById('signup-name').value.trim(),password=document.getElementById('password').value,next=authNext();try{if(!validEmail(email))throw new Error('Enter a valid email address.');if(password.length<8)throw new Error('Use at least 8 characters for your password.');if(!document.getElementById('accept-terms').checked)throw new Error('Accept the terms and privacy notice to continue.');if(commerce.accounts[email])throw new Error('This preview email already exists. Sign in instead.');const salt=uid();commerce.accounts[email]={identity:{id:uid(),email,name,confirmed:false},salt,hash:await passwordHash(password,salt),receipts:[],study:freshStudy()};persistCommerce();go('verify-email',{email,next});}catch(e){errorAt(e.message);}}
async function verifyPreviewEmail(){try{if(document.getElementById('verify-code').value!=='246810')throw new Error('Use preview code 246810.');const a=commerce.accounts[data.email];if(!a)throw new Error('Create a preview account first.');a.identity.confirmed=true;storeStudy();commerce.active=data.email;state={...freshStudy(),...a.study,name:a.identity.name};save();go(authNext());}catch(e){errorAt(e.message);}}
async function loginPreview(){try{const email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value,a=commerce.accounts[email];if(!a||a.hash!==await passwordHash(password,a.salt))throw new Error('Email or password did not match.');if(!a.identity.confirmed){go('verify-email',{email,next:'plans'});return;}storeStudy();commerce.active=email;state={...freshStudy(),...a.study,name:a.study?.name||a.identity.name};save();go('today');}catch(e){errorAt(e.message);}}
function logoutPreview(){storeStudy();commerce.active=null;state={...freshStudy(),...(commerce.guest||{})};save();stack=[];go('sign-in');toast('Signed out. Your purchase and history stay with your account.');}
function requestRecovery(){const email=document.getElementById('email').value.trim().toLowerCase();if(!validEmail(email)){errorAt('Enter a valid email address.');return;}go('reset-password',{email});}
async function resetPreviewPassword(){try{const email=data.email||currentIdentity()?.email,a=commerce.accounts[email],password=document.getElementById('password').value,confirm=document.getElementById('confirm-password').value;if(document.getElementById('recovery-code').value!=='246810')throw new Error('Use preview recovery code 246810.');if(password.length<8)throw new Error('Use at least 8 characters.');if(password!==confirm)throw new Error('Your passwords do not match.');if(!a)throw new Error('No local preview account found.');a.salt=uid();a.hash=await passwordHash(password,a.salt);persistCommerce();go('sign-in');toast('Preview password updated. Your purchase is unchanged.');}catch(e){errorAt(e.message);}}
function beginPurchase(){if(!currentIdentity()){go('sign-up',{next:'checkout'});return;}if(accessNow().kind==='paid'){go('membership');return;}showSheet('Preview store confirmation',`<div class="row between"><strong>Ontario G1 Complete</strong><strong>CA$14.99</strong></div><p class="muted">This simulates the Apple/Google confirmation sheet. No real payment method is requested and no money is charged.</p>${btn('Confirm test purchase','completePurchase()')}${btn('Cancel purchase',"closeSheet();toast('Purchase cancelled. No charge.');go('checkout')",'secondary','')}`);}
function grantPreviewPurchase(){const a=currentAccount();if(!a)return;if(accessNow().kind==='paid'){go('membership');return;}a.paid={startsAt:new Date(now()).toISOString(),endsAt:null,lifetime:true};a.receipts.push({id:'DEMO-'+uid().slice(0,8).toUpperCase(),createdAt:new Date(now()).toISOString(),amount:'CA$14.99',status:'simulated',lifetime:true});a.pending=false;persistCommerce();go('payment-success');}
function completePurchase(){closeSheet();const outcome=commerce.storeOutcome||'success';if(outcome==='cancelled'){go('checkout',{cancelled:true});return;}if(outcome==='declined'){go('checkout',{error:'The test payment was declined. Your free access has not changed. Choose another test outcome and retry.'});return;}if(outcome==='pending'){currentAccount().pending=true;persistCommerce();go('checkout',{pending:true});return;}grantPreviewPurchase();}
function checkPreviewPurchase(){if(currentAccount()?.pending){if(commerce.storeOutcome==='success'){grantPreviewPurchase();}else toast('Still pending. Change Preview tools → Store response to Success, then check again.');}else if(accessNow().full){go('membership');toast('Ontario G1 Complete is already unlocked.');}else{go('membership');toast('No paid purchase found for this preview account.');}}
function setStoreOutcome(outcome){commerce.storeOutcome=outcome;persistCommerce();toast('Preview store response: '+outcome);}
function refundPreview(){const a=currentAccount();if(!a?.paid){toast('No test purchase to refund.');return;}a.paid.revokedAt=new Date(now()).toISOString();a.receipts.forEach(r=>r.status='refunded');persistCommerce();if(state.active&&state.active.questionIds.some(id=>!allowedNow(id))){state.pausedPremium=state.active;state.active=null;save();}go('membership');toast('Test refund applied. Complete access is revoked.');}
function clearPracticePreview(){showSheet('Clear practice history?',`<p class="muted">Your answers, bookmarks and sessions on this device will be removed. A verified purchase stays attached to the account.</p>${btn('Clear practice history',"state.sessions=[];state.bookmarks=[];state.active=null;state.pausedPremium=null;save();closeSheet();go('account');toast('Practice cleared. Purchase unchanged.')",'danger','trash')}${btn('Keep my history','closeSheet()','secondary','')}`);}
function deletePreviewAccount(){showSheet('Delete your preview account?',`${field('Type DELETE to confirm','delete-confirm','DELETE')}<p class="muted">This permanently removes this local test account and its test history. It does not issue a real refund.</p>${btn('Delete test account',"if(document.getElementById('delete-confirm').value!=='DELETE'){toast('Type DELETE to confirm.');}else{const email=commerce.active;delete commerce.accounts[email];commerce.active=null;state=freshStudy();persistCommerce();save();closeSheet();stack=[];go('welcome');}",'danger','trash')}`);}
function clearAllPreview(){showSheet('Reset the entire simulator?',`<p class="muted">Developer preview control: removes every local test account, simulated receipt and study history in this browser.</p>${btn('Reset simulator',"localStorage.removeItem(COMMERCE_KEY);localStorage.removeItem('firstlane-design-preview');location.href=location.pathname",'danger','trash')}${btn('Keep preview data','closeSheet()','secondary','')}`);}
reset=clearAllPreview;
finishOnboarding=function(){state.name=document.getElementById('first-name')?.value||state.name;state.onboarded=true;save();go('sign-up');};
const oldBegin=begin;begin=function(mode='quick',topic){const a=accessNow();if(!ensureFeature(mode))return;if(a.full&&!state.active&&state.pausedPremium){state.active=state.pausedPremium;state.pausedPremium=null;save();go('quiz');return;}if(state.active){if(state.active.questionIds.some(id=>!allowedNow(id))||!canUseFeature(state.active.mode,a)){go('locked',{reason:'resume'});return;}go('quiz');return;}const ids=mode==='saved'?state.bookmarks:latestMistakes(state.sessions),selected=selectQuestions(samplePool(),{mode,topic,ids,count:a.kind==='guest'?10:state.goal});if(!selected.length){if(!a.full&&mode==='topic')go('locked',{reason:'topic'});else toast('No available questions here yet. Try your free samples.');return;}const names={quick:a.full?'Daily practice':a.kind==='guest'?'10-question guest preview':'Free sample practice',topic:topic||'Topic practice',mock:'40-question rehearsal',mistakes:'Mistake review',saved:'Saved questions'};state.active={id:uid(),mode,title:names[mode],questionIds:selected.map(q=>q.id),answers:[],index:0,startedAt:new Date(now()).toISOString()};picked=null;save();go('quiz');};
const oldAnswerNext=answerNext;answerNext=function(){const s=state.active;if(!s||s.questionIds.some(id=>!allowedNow(id))||!canUseFeature(s.mode,accessNow())){go('locked',{reason:'access'});return;}oldAnswerNext();};
const oldBookmark=bookmark;bookmark=function(id){if(!allowedNow(id)){go('locked',{reason:'question'});return;}oldBookmark(id);};
const originalViews={...views};
views.welcome=function(){let html=originalViews.welcome();html=html.replace(chip('EARLY ACCESS','spark'),chip('FREE TO START','spark')).replace(btn('Find your starting point',"go('destination')"),btn('Create my free account',"go('sign-up')")+btn('Try 10 guest questions','previewGuest()','secondary',''));return html;};
views.goal=function(){return originalViews.goal().replace('No account or payment is needed to explore this preview.','40 fixed samples are free after sign-up. Ontario G1 Complete is always an explicit one-time purchase.').replace('Let’s take the first step','Create my free account');};
views.today=function(){return originalViews.today().replace('<div class="hero-card">',accessCard()+'<div class="hero-card">');};
views.study=function(){return accessCard()+originalViews.study();};
views.topic=function(){const name=topicNames[data.id||0],count=samplePool().filter(q=>q.topic===name).length;return originalViews.topic()+(!accessNow().full?note(`${count} question${count===1?'':'s'} in your fixed sample pool. The complete topic bank is included with Ontario G1 Complete.`):'');};
views.locked=function(){const a=accessNow();return `${topBar('Complete access')}<div class="lock-art">${ART.logo}</div>${chip('ONTARIO G1 COMPLETE','lock',true)}${title('A little more<br>room to learn.','This feature is part of the complete Ontario pack. Your practice history is safe.')}${card(`<strong class="title">${a.kind==='guest'?'10 guest questions':'40 free sample questions'}</strong><p class="muted">Free practice repeats the same fixed samples. The remaining questions, full rehearsals and offline practice unlock with one purchase.</p>`)}${btn(a.kind==='guest'?'Create a free account':'See Ontario G1 Complete',`go('${a.kind==='guest'?'sign-up':'plans'}')`)}${state.active?btn('Save session & return to samples',"state.pausedPremium=state.active;state.active=null;save();go('today')",'secondary',''):btn('Keep practising free samples',"go('today')",'secondary','')}${note('Ontario G1 Complete is CA$14.99 once. No subscription and no expiry.')}`;};
views.plans=function(){const a=accessNow();return `${topBar('Plans & access')}<div class="plan-heading">${chip('SIMPLE BY DESIGN','spark',true)}${title('Start free.<br>Unlock it once.','40 free samples. One Ontario purchase when you want the complete pack.')}</div><div class="plan-illustration">${ART.road}</div><div class="plus-card"><div class="row between"><h2>Ontario G1 Complete</h2>${chip('ONE-TIME','',true)}</div><div class="price">CA$14.99 <span>once</span></div><p>Pay once. Keep your Ontario G1 access.<br>No subscription. No expiry.</p><div class="benefits">${['All 500 practice questions','Topic practice and full rehearsals','Clear explanations and mistake review','Offline practice in the installed app','Ontario pack updates and corrections'].map(t=>`<div class="row">${ic('check',17)}<span>${t}</span></div>`).join('')}</div>${btn(a.kind==='paid'?'View my purchase':'Unlock Ontario G1 Complete',`go('${a.kind==='paid'?'membership':currentIdentity()?'checkout':'sign-up'}',${currentIdentity()?'{}':"{next:'checkout'}"})`)}<p class="tiny" style="text-align:center">Ontario only. Final price and tax shown by your store.</p></div>${card(`<div class="row between"><h2 class="title" style="font-size:23px">FirstLane Free</h2>${chip(!a.full?'Your plan':'Always available')}</div><div class="price">CA$0 <span>/ forever</span></div><p class="muted">40 fixed sample questions after sign-up. Repeat your samples, review mistakes and keep your progress.</p><p class="muted small">Guests can try 10 of those questions. Repeating sessions never unlocks the full bank.</p>${btn(currentIdentity()?'Continue with FirstLane Free':'Create free account',currentIdentity()?"go('today')":"go('sign-up')",'secondary','')}`)}${btn('Restore purchase / check access',"go('membership')",'ghost','refresh')}${btn('Terms, privacy & refund information',"go('legal')",'ghost','')}${note('REVIEW BUILD · The bank remains draft content. Accounts and purchases in this companion are simulated, not live services.','warning')}`;};
views['sign-up']=function(){return `${topBar()}${logo()}${title('Your practice.<br>Your account.','40 sample questions. Your own progress. No payment required.','GET ROAD READY.')}${chip('FREE ACCOUNT · NO CARD NEEDED','shield')}${field('First name','signup-name','What should we call you?','text',state.name)}${field('Email address','email','you@example.com','email')}${passwordField()}<label class="terms-check"><input type="checkbox" id="accept-terms"><span>I agree to the <button class="inline-link" type="button" onclick="go('legal')">terms and privacy notice</button>.</span></label>${formError()}${btn('Create my free account','createPreviewAccount()')}<p class="muted small" style="text-align:center">Creating an account is free.<br>Ontario Complete is always a separate purchase.</p>${btn('Already have an account? Sign in',"go('sign-in')",'secondary','')}${btn('Try 10 guest questions instead','previewGuest()','ghost','')}${note('LOCAL PREVIEW ACCOUNT · Use a test email and a throwaway password, not real credentials. No email is sent.')}`;};
views['verify-email']=function(){return `${topBar('Verify your email')}<div class="mail-symbol">${ic('shield',42)}</div>${title('Check your inbox.<br>Get road ready.',`Enter the code for ${escape(data.email||'your email')}.`,'ONE LAST STEP')}${field('Verification code','verify-code','6-digit code','text')}${formError()}${btn('Verify & choose my access','verifyPreviewEmail()')}${btn('Resend code',"toast('Preview code: 246810. No real email is sent.')",'secondary','refresh')}${note('Preview verification code: 246810. No real email has been sent.')}<p class="muted small">Verification never charges you. It keeps progress and purchases attached to the correct account.</p>${btn('Use a different email',"go('sign-up')",'ghost','')}`;};
views['sign-in']=function(){return `${topBar()}${logo()}${title('Pick up where<br>you left off.','Your progress and purchase belong to this account.','WELCOME BACK')}${field('Email address','email','you@example.com','email')}${passwordField()}${formError()}${btn('Sign in','loginPreview()')}${btn('Forgot your password?',"go('forgot-password')",'ghost','')}${btn('Create a free account',"go('sign-up')",'secondary','')}${btn('Try 10 guest questions','previewGuest()','ghost','')}${note('Sign in to a local preview account created in this browser. Real Supabase accounts are separate.')}`;};
views['forgot-password']=function(){return `${topBar('Password recovery')}${title('A fresh start.<br>Same progress.','We’ll help you find your way back. Your purchase stays attached to your account.')}${field('Email address','email','you@example.com','email')}${formError()}${btn('Send recovery code','requestRecovery()')}${btn('Back to sign in',"go('sign-in')",'ghost','')}${note('This preview does not send email. Recovery is simulated with code 246810.')}`;};
views['reset-password']=function(){return `${topBar('Set a new password')}${title('Back on track.','Use a throwaway password for this local preview.')}${field('Recovery code','recovery-code','6-digit code')}${passwordField('New password')}${field('Confirm new password','confirm-password','Enter it again','password')}${formError()}${btn('Save new password','resetPreviewPassword()')}${note('Preview recovery code: 246810. This changes only your local test account password.')}`;};
views.checkout=function(){const account=currentAccount(),pending=data.pending||account?.pending;if(accessNow().kind==='paid')return `${topBar()}${title('Ontario G1 Complete is yours.','There is no need to purchase again.')}${btn('View purchase',"go('membership')")}`;return `${topBar('Review purchase')}${title('Unlock it once.<br>Keep moving.','Complete Ontario G1 preparation without a recurring bill.','ONE PURCHASE. YOUR ONTARIO PACK.')}${card(`<div class="row between">${chip('ONTARIO G1 COMPLETE','spark',true)}${chip('NO EXPIRY')}</div><h2 class="title" style="font-size:26px">Full Ontario G1 pack</h2><p class="muted">One purchase unlocks the Ontario pack for this FirstLane account. It does not renew and does not expire.</p><div class="checkout-total"><strong>Pay once</strong><span>CA$14.99</span></div><p class="muted small">Apple or Google shows the real confirmation sheet. FirstLane never asks for card details.</p>`)}${card('<h2 class="title">What you keep</h2><p class="muted">Full question bank, topic practice, rehearsals, explanations, mistake review and offline practice for Ontario G1. Future jurisdictions are separate products.</p>')}${data.error?note(data.error,'warning'):''}${data.cancelled?note('Purchase cancelled. No charge and no access change.'):''}${pending?`${note('Purchase submitted. Waiting for verification. Do not purchase again while it is pending.')}${btn('Check purchase status','checkPreviewPurchase()','secondary','refresh')}${btn('Payment help',"go('support')",'ghost','help')}`:`${btn('Simulate CA$14.99 purchase','beginPurchase()')}${btn('Not now',"go('plans')",'ghost','')}`}${note('PREVIEW CHECKOUT · No store transaction occurs in this browser.','warning')}`;};
views['payment-success']=function(){const a=accessNow();return `${topBar()}<div class="success-art">${ART.trophy}</div>${title(a.kind==='paid'?'You’re in.<br>Keep moving.':'Check your<br>access first.',a.kind==='paid'?'Ontario G1 Complete is yours. No countdown and no renewal.':'No verified paid access is available.',a.kind==='paid'?'PREVIEW PURCHASE COMPLETE':'ACCESS CHECK')}${card(`${chip(a.label,'spark',a.full)}<p class="muted">${escape(accessDescription(a,now()))}</p><p class="muted small">This was a simulation. No money was charged.</p>`)}${btn('Start practising',"go('today')")}${btn('View purchase & receipt',"go('membership')",'secondary','')}`;};
views.membership=function(){const a=accessNow(),account=currentAccount();return `${topBar('Plan & billing')}${title('Simple access.<br>Nothing on repeat.','Your free access or one-time Ontario purchase, all in one place.')}${card(`<div class="row between">${chip(a.label,'spark',a.full)}${chip('ONTARIO G1')}</div><h2 class="title" style="font-size:25px">${a.full?'Complete preparation':'Your free starting point'}</h2><p class="muted">${escape(accessDescription(a,now()))}</p><p class="muted small">${a.kind==='paid'?'This purchase has no renewal and no access expiry. A refund can revoke access.':'Free access stays free. Unlock Ontario G1 Complete whenever you want the full pack.'}</p>${a.kind!=='paid'?btn('See Ontario G1 Complete',"go('plans')"):''}`)}${btn('Restore purchase / refresh access',account?'checkPreviewPurchase()':"go('sign-in')",'secondary','refresh')}${note('Use the same FirstLane account you purchased with. Clearing practice history or signing out does not remove a verified purchase.')}${head('Payment history')}${account?.receipts.length?account.receipts.map(r=>card(`<div class="row between"><strong>Ontario G1 Complete</strong>${chip(r.status)}</div><p class="muted">${escape(r.amount)} · ${new Date(r.createdAt).toLocaleDateString()}</p><p class="muted tiny">Reference: ${escape(r.id)}</p><p class="muted tiny">Preview receipt. Not a tax invoice or real transaction.</p>`)).join(''):card('<strong>No purchases yet</strong><p class="muted">Your free access never creates a charge.</p>')}${btn('Payment help & refunds',"go('support')",'ghost','help')}`;};
views.profile=function(){const a=currentIdentity();return `<div class="eyebrow">YOUR PRACTICE, YOUR PACE</div><div class="row"><div class="avatar">${escape(state.name?.slice(0,2).toUpperCase()||'L.')}</div><div class="grow column"><h1 class="heading" style="font-size:26px">${escape(state.name||'Your next chapter')}</h1><p class="muted small">${escape(a?.email||'Guest · saved on this device')}</p></div></div>${accessCard()}${!a?btn('Sign up — it’s free',"go('sign-up')"):''}<div>${[['spark','Plan & billing','One-time purchase, receipts and restore','membership'],['user','Your account',a?'Security and data controls':'Create an account or sign in','account'],['map','Test location','Ontario G1 · Canada','jurisdiction'],['target','Study plan',state.goal+' questions a day','study-plan'],['download','Offline packs','Included with Ontario Complete','downloads'],['sun','Appearance & accessibility','Theme, motion and haptics','appearance'],['help','Help & support','A little guidance when you need it','support'],['shield','Privacy & terms','','legal']].map(([i,h,s,p])=>menu(i,h,s,`go('${p}')`)).join('')}</div>${a?btn('Sign out','logoutPreview()','ghost','logout'):btn('Already a member? Sign in',"go('sign-in')",'ghost','')}${btn('Content review status',"go('content')",'ghost','book')}<p class="muted tiny" style="text-align:center">FIRSTLANE 0.3.0 · LOCAL SIMULATOR<br>Not an official licensing service.</p>`;};
views.account=function(){const a=currentIdentity();return `${topBar('Your account')}${title('A place for<br>your progress.',a?escape(a.email):'Guests get 10 sample questions. Sign up for 40 fixed free samples.')}${field('Display name','display-name','Your first name','text',state.name,'state.name=this.value;save()')}${a?`${btn('Plan & billing',"go('membership')")}${btn('Change password',`go('reset-password',{email:${JSON.stringify(a.email)}})`,'secondary','lock')}${btn('Sign out','logoutPreview()','ghost','logout')}${note('Local preview account. Real native accounts use Supabase. This companion does not back up to a cloud service.')}${menu('trash','Clear practice history','Your purchase remains attached to your account','clearPracticePreview()')}${menu('trash','Delete test account','Delete this local account permanently','deletePreviewAccount()')}`:`${btn('Create a free account',"go('sign-up')")}${btn('Sign in instead',"go('sign-in')",'secondary','')}${note('Free accounts stay free. Ontario G1 Complete is always an explicit one-time purchase from Plans.')}`}`;};
views.downloads=function(){if(!accessNow().full)return `${topBar('Offline packs')}${title('Take Ontario<br>off the grid.','Offline study is included with Ontario G1 Complete.')}${accessCard()}${btn('See Ontario G1 Complete',"go('plans')")}`;return `${topBar('Offline packs')}<div class="mail-symbol">${ic('download',44)}</div>${title('Your practice,<br>without the signal.','Your Ontario purchase has no access expiry.')}${card(`<h2 class="title">Ontario G1</h2><p class="muted">500 draft questions · English</p>${chip(state.downloaded?'Saved locally':'Available','',state.downloaded)}${btn(state.downloaded?'Remove downloaded copy':'Save review pack',"state.downloaded=!state.downloaded;save();render();toast(state.downloaded?'Preview download saved.':'Preview download removed.')",state.downloaded?'secondary':'','download')}`)}${note('The companion already contains the draft bank. Native download controls write to SQLite; production needs approved protected pack delivery.','warning')}`;};
const originalQuestion=originalViews.question;views.question=function(){const id=data.id||bank[0].id;if(!allowedNow(id))return views.locked();return originalQuestion();};
views['session-review']=function(){const s=state.sessions.find(s=>s.id===data.id)||state.sessions.at(-1);return `${topBar('Session review')}${title('Make every<br>answer count.','Scores stay saved. Complete-pack explanations require purchase access.')}${s?s.answers.map((a,i)=>{const q=byId.get(a.questionId),read=allowedNow(q.id);return `<button class="card" style="color:var(--text);text-align:left" onclick="go('${read?'question':'locked'}',{id:'${q.id}',chosen:'${a.optionId}'})"><div class="row">${ic(read?(a.correct?'check':'refresh'):'lock')}<div class="grow column"><div class="eyebrow">QUESTION ${i+1} · ${a.correct?'CORRECT':'REVISIT'}</div><strong>${read?escape(q.prompt):'Saved Complete question'}</strong><p class="muted small">${read?escape(q.explanation):'Unlock Ontario G1 Complete to review this explanation.'}</p></div></div></button>`;}).join(''):empty('Session not found','Complete a session first.')}`;};
for(const mode of ['review','saved']){views[mode]=function(){const ids=(mode==='saved'?state.bookmarks:latestMistakes(state.sessions)),readable=ids.filter(allowedNow);return `${topBar(mode==='saved'?'Saved questions':'Mistake review')}${title(mode==='saved'?'Keep the useful<br>ones close.':'This is where<br>it starts to stick.','Free sample review stays free. Complete-pack questions follow your current access.')}${readable.length?btn('Practise these questions',`begin('${mode==='saved'?'saved':'mistakes'}')`):empty('Nothing available here yet','Save or answer a sample question to start your review list.','Start practising',"begin('quick')")}${readable.map(id=>{const q=byId.get(id);return `<button class="card" style="color:var(--text);text-align:left" onclick="go('question',{id:'${id}'})"><strong>${escape(q.prompt)}</strong><p class="muted small">${escape(q.topic)}</p></button>`;}).join('')}${ids.length>readable.length?note(`${ids.length-readable.length} saved Complete questions are locked. Your history is not deleted.`):''}`;};}
views.legal=function(){return `${topBar('Privacy & terms')}${title('Clear by design.','The access model, without the small-print surprises.')}${[['Free really means free','Guests can try 10 fixed questions. Verified accounts get 40 fixed samples, results and sample review indefinitely. Free sessions reuse that pool.'],['The paid unlock','Ontario G1 Complete is CA$14.99 once in this proposed launch model. It has no automatic renewal and no access expiry for the Ontario pack. The real store shows final local price and tax.'],['Future locations','Ontario ownership does not automatically unlock future Canadian provinces, US states or other jurisdictions.'],['Payment and refunds','The native app uses the App Store or Google Play with RevenueCat coordinating entitlement status. This browser companion uses simulated receipts only. A store refund can revoke access.'],['Data and accounts','This companion stores test accounts and study data locally. Do not enter real passwords or payment details. Connected native accounts use Supabase. Clearing study history does not remove a verified store purchase.'],['Learning, not certification','The question bank is a source-linked draft, not independently approved or MTO-endorsed. Practice scores are not pass guarantees.'],['Before public launch','The operator’s identity, contact information, privacy retention policy, final legal terms, content rights, billing configuration and device testing must be completed.']].map(([h,b])=>card(`<h2 class="title">${h}</h2><p class="muted">${b}</p>`)).join('')}`;};
views.support=function(){return `${topBar('Help & support')}${title('A little guidance.<br>A clearer road.','Find your access, payment and account answers here.')}${menu('spark','What is free?','Guest, Free and Ontario Complete explained',"go('plans')")}${menu('refresh','Restore a purchase','Sign in to the same FirstLane account',"go('membership')")}${menu('lock','Cannot sign in?','Recover your account password',"go('forgot-password')")}${card('<h2 class="title">Is this a subscription?</h2><p class="muted">No. Ontario G1 Complete is a one-time purchase in the proposed launch model. There is no automatic renewal and no access expiry.</p>')}${card('<h2 class="title">Why did a question lock?</h2><p class="muted">The question is outside the fixed free sample pool. Unlock Ontario G1 Complete to access the full bank.</p>')}${card('<h2 class="title">Payment pending or refunded?</h2><p class="muted">Do not purchase again while verification is pending. A refunded purchase revokes Complete access according to the store process.</p>')}${btn('Send feedback',"go('report')",'secondary','flag')}${note('Preview reports are stored locally, not sent to a support team. Configure the real support channel before launch.')}`;};
var previousAccess;const originalRender=render;render=function(){if(page==='quiz'&&state.active&&(state.active.questionIds.some(id=>!allowedNow(id))||!canUseFeature(state.active.mode,accessNow()))){page='locked';data={reason:'access'};}previousAccess=accessNow().kind;originalRender();};
const side=document.querySelector('.studio-side');if(side){const controls=document.createElement('div');controls.className='preview-tools';controls.innerHTML=`<div class="studio-label">PREVIEW TOOLS · NOT LIVE BILLING</div><label for="store-response">Simulated store response</label><select id="store-response" onchange="setStoreOutcome(this.value)"><option value="success">Success</option><option value="declined">Payment declined</option><option value="cancelled">User cancelled</option><option value="pending">Pending verification</option></select><div class="studio-controls"><button onclick="refundPreview()">Test refund</button></div><p>Use code <strong>246810</strong> for preview email and recovery. Never use real credentials.</p>`;side.append(controls);document.getElementById('store-response').value=commerce.storeOutcome;}
previousAccess=accessNow().kind;setInterval(()=>{const next=accessNow().kind;if(next!==previousAccess){previousAccess=next;render();}},1000);render();
