import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {shuffle,selectQuestions,checkAnswer,summarize,latestMistakes,activity,validateBank,localDay} from '../src/domain/engine.mjs';
const content=JSON.parse(await readFile(new URL('../content/ontario-g1.draft.json',import.meta.url),'utf8'));const bank=content.questions;
function rng(seed=12345){return()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
const answer=(q,correct=true,at='2026-10-03T12:00:00.000Z')=>({questionId:q.id,conceptId:q.concept_id,optionId:q.correct_option_id,correct,at,section:q.section});
test('500 structurally valid source-linked draft questions',()=>{assert.equal(bank.length,500);assert.deepEqual(validateBank(content),[]);assert.equal(new Set(bank.map(q=>q.prompt)).size,500);assert.equal(new Set(bank.map(q=>q.concept_id)).size,250);assert.equal(bank.filter(q=>q.section==='road_signs').length,200);assert.equal(bank.filter(q=>q.section==='road_rules').length,300);});
test('draft status is preserved for every question',()=>{assert.ok(bank.every(q=>q.review.publication_status==='draft'&&!q.review.publishable));});
test('shuffle returns permutation without mutating input',()=>{const a=[1,2,3,4,5],b=shuffle(a,rng());assert.deepEqual(a,[1,2,3,4,5]);assert.deepEqual([...b].sort(),a);assert.notDeepEqual(a,b);});
test('correctness follows stable IDs after option shuffling',()=>{for(const q of bank){const mixed={...q,options:shuffle(q.options,rng())};assert.equal(checkAnswer(mixed,q.correct_option_id),true);for(const o of mixed.options.filter(o=>o.id!==q.correct_option_id))assert.equal(checkAnswer(mixed,o.id),false);}});
test('invalid option is rejected rather than accepted as wrong',()=>assert.throws(()=>checkAnswer(bank[0],'outside-question')));
test('daily practice goals are correctly balanced with no paired concepts',()=>{for(const count of[5,10,20]){const rows=selectQuestions(bank,{mode:'quick',count},rng());assert.equal(rows.length,count);assert.equal(new Set(rows.map(q=>q.concept_id)).size,count);assert.equal(rows.filter(q=>q.section==='road_signs').length,Math.ceil(count/2));}});
test('100 rehearsal sessions contain 20 signs and 20 rules, without paired concepts',()=>{for(let i=0;i<100;i++){const rows=selectQuestions(bank,{mode:'mock'},rng(i+1));assert.equal(rows.length,40);assert.equal(rows.filter(q=>q.section==='road_signs').length,20);assert.equal(rows.filter(q=>q.section==='road_rules').length,20);assert.equal(new Set(rows.map(q=>q.concept_id)).size,40);}});
test('never mixes other jurisdictions',()=>{const foreign={...bank[0],id:'foreign',pack_key:'US-CA-C'};assert.ok(selectQuestions([foreign,...bank],{mode:'mock'},rng()).every(q=>q.pack_key==='CA-ON-G1'));});
test('topic selection only uses that topic',()=>{const topic=bank[100].topic;const chosen=selectQuestions(bank,{mode:'topic',topic,count:10},rng());assert.ok(chosen.length>0);assert.ok(chosen.every(q=>q.topic===topic));});
test('saved and mistake modes cannot include unrequested items',()=>{const ids=[bank[0].id,bank[12].id];for(const mode of['saved','mistakes'])assert.ok(selectQuestions(bank,{mode,ids,count:20},rng()).every(q=>ids.includes(q.id)));assert.equal(selectQuestions(bank,{mode:'saved',ids:[]}).length,0);});
test('latest correct attempt clears a conceptual mistake across paired variants',()=>{const q=bank[0],pair=bank.find(x=>x.concept_id===q.concept_id&&x.id!==q.id);const earlier={answers:[answer(q,false)]},later={answers:[answer(pair,true,'2026-10-03T13:00:00Z')]};assert.deepEqual(latestMistakes([earlier]),[q.id]);assert.deepEqual(latestMistakes([later,earlier]),[]);});
test('summary reports actual denominators and handles zero',()=>{assert.equal(summarize([]).accuracy,0);const result=summarize([answer(bank[0]),answer(bank[1],false),answer(bank[300])]);assert.equal(result.correct,2);assert.equal(result.accuracy,67);assert.deepEqual(result.sections.map(s=>s.total),[2,1]);});
test('streak counts local calendar days and permits yesterday as latest',()=>{const now=new Date(2026,9,3,12),q=bank[0],sessions=[{answers:[answer(q,true,new Date(2026,9,1,12).toISOString()),answer(q,true,new Date(2026,9,2,12).toISOString())]}];const a=activity(sessions,now);assert.equal(a.streak,2);assert.equal(a.today,0);assert.equal(a.week.length,7);assert.equal(a.concepts,1);assert.equal(localDay(now),'2026-10-03');});
test('validator catches duplicate revisions and bad answer IDs',()=>{const q={...bank[0],correct_option_id:'bad'};assert.ok(validateBank({...content,questions:[q,q]}).length>=3);});
