import React,{useEffect,useState} from 'react';
import {useRouter} from 'expo-router';
import {useApp} from '../src/state/AppState';
import {config} from '../src/config';
import {paymentHistory,restoreAccess} from '../src/lib/billing';
import {accessDescription} from '../src/domain/access.mjs';
import {Button,Card,Chip,Copy,Heading,Muted,Note,Row,Screen} from '../src/components/UI';
export default function Membership(){
 const router=useRouter(),{identity,access,accessRecords,reloadAccess,notify}=useApp();
 const [history,setHistory]=useState<{owner:string;receipts:any[]}>({owner:'',receipts:[]}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const receipts=history.owner===identity?.id?history.receipts:[];
 useEffect(()=>{let active=true;setError('');setHistory({owner:'',receipts:[]});if(!identity?.confirmed)return;const owner=identity.id;setLoading(true);
  const task=config.mode==='demo'?Promise.resolve(accessRecords.receipts||[]):paymentHistory(owner);
  task.then(items=>{if(active)setHistory({owner,receipts:items});}).catch(()=>{if(active)setError('Payment history could not be loaded. Your purchase has not been removed.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};
 },[identity?.id,identity?.confirmed,accessRecords,retry]);
 return <Screen back title="Plan & billing"><Heading sub="Your free access or one-time Ontario purchase, all in one place.">Simple access.{`\n`}Nothing on repeat.</Heading><Card><Row style={{justifyContent:'space-between',flexWrap:'wrap'}}><Chip selected={access.full}>{access.label}</Chip><Chip>ONTARIO G1</Chip></Row><Copy size={23} weight="700">{access.full?'Complete preparation':'Your free starting point'}</Copy><Muted>{accessDescription(access)}</Muted><Muted size={12}>{access.kind==='paid'?'This purchase does not renew and has no access expiry. A refund can revoke access.':'Free access stays free. Unlock Ontario G1 Complete whenever you are ready.'}</Muted>{!access.full&&<Button onPress={()=>router.push('/plans')}>See Ontario G1 Complete</Button>}</Card><Button kind="secondary" icon="refresh" onPress={async()=>{if(!identity){router.push('/auth/sign-in');return;}if(!identity.confirmed){router.push({pathname:'/auth/verify-email',params:{email:identity.email}});return;}if(config.mode==='connected')await restoreAccess(identity.id);await reloadAccess(true);setRetry(n=>n+1);notify('Purchase status refreshed for this FirstLane account.');}}>Restore purchase / refresh access</Button><Note>Restore using the FirstLane account that made the purchase. Signing out or clearing practice history does not remove a verified purchase.</Note><Copy size={21} weight="700">Payment history</Copy>{loading?<Muted>Loading payment history…</Muted>:error?<><Note tone="warning">{error}</Note><Button kind="secondary" onPress={()=>setRetry(n=>n+1)}>Retry</Button></>:receipts.length?receipts.map(x=><Card key={x.id}><Row style={{justifyContent:'space-between',flexWrap:'wrap'}}><Copy weight="700">Ontario G1 Complete</Copy><Chip>{x.status||'Verified'}</Chip></Row><Muted>{x.amount||x.display_price||'Store purchase'} · {Number.isFinite(Date.parse(x.createdAt||x.purchased_at))?new Date(x.createdAt||x.purchased_at).toLocaleDateString():'Date unavailable'}</Muted><Muted size={11}>Reference: {x.id}</Muted>{config.mode==='demo'&&<Muted size={11}>Simulated receipt. Not a real transaction or tax invoice.</Muted>}</Card>):<Card><Copy weight="700">No purchases to show</Copy><Muted>{identity?.confirmed?'Free access never creates a charge.':'Sign in with a verified account to view purchases.'}</Muted></Card>}<Button kind="ghost" onPress={()=>router.push('/support')}>Payment help & refunds</Button></Screen>;
}
