// Public links only; generated by build-landing.mjs
window.LANE_SITE_CONFIG = {
  "apple": "",
  "google": "",
  "privacy": "",
  "terms": "",
  "deletion": "",
  "supportEmail": "",
  "operator": "",
  "released": false
};
