import fs from 'node:fs';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';
import {OFFER} from '../src/domain/offer.mjs';import {loadEnvironment} from './load-environment.mjs';
const root=fileURLToPath(new URL('..',import.meta.url));loadEnvironment(root);
const released=process.argv.includes('--release');
const config={apple:process.env.LANE_APP_STORE_URL||'',google:process.env.LANE_GOOGLE_PLAY_URL||'',privacy:process.env.EXPO_PUBLIC_PRIVACY_URL||'',terms:process.env.EXPO_PUBLIC_TERMS_URL||'',deletion:process.env.EXPO_PUBLIC_ACCOUNT_DELETION_URL||'',supportEmail:process.env.EXPO_PUBLIC_SUPPORT_EMAIL||'',operator:process.env.EXPO_PUBLIC_OPERATOR_NAME||'',released};
if(released){const {releaseIssues}=createRequire(import.meta.url)('./release-policy.cjs');const issues=releaseIssues(root,process.env);for(const [key,host] of [['apple','apps.apple.com'],['google','play.google.com']]){try{const u=new URL(config[key]);if(u.protocol!=='https:'||u.hostname!==host)throw Error();}catch{issues.push('Missing genuine '+key+' store URL.');}}if(issues.length)throw new Error(issues.join('\n'));}
fs.writeFileSync(new URL('../landing/config.js',import.meta.url),'// Public links only; generated by build-landing.mjs\nwindow.LANE_SITE_CONFIG = '+JSON.stringify(config,null,2)+';\n');
const file=new URL('../landing/index.html',import.meta.url);let html=fs.readFileSync(file,'utf8');html=html.replace(/CA\$\d+\.\d{2}/g,(price)=>price==='CA$0.00'?price:OFFER.priceLabel);fs.writeFileSync(file,html);
console.log(released?'Release landing configured. Upload landing/ only.':'Prelaunch landing configured. Missing store links are visibly unavailable.');
